### ISSUE TITLE
Implement Force Feedback and GameController  support

### ISSUE THREAD

**Issue by desiderantes** [Serranya/sdl2-vapi#1]
I'm really interested in how do you plan to bind those subsystems, and i hope you do it better than my version. Also, since documentation is sparse regarding Force Feedback, some code examples would be great :smile:

**Comment by Serranya** [comment]
I have locally some code examples to test my Bindings. I will clean them up a little and ad them either in this repo or a seperate one.

In parallel im implementing the tutorials from http://lazyfoo.net/tutorials/SDL/index.php in this repo:
https://github.com/Serranya/sdl2-vala-lazy-foo

You can find some examples there too

**Comment by desiderantes** [comment]
Nice, thanks! Yes, a separate repo would be cool. I wanted to ask you, why start the bindings from scratch? Why not reuse PedroHLC version, or my version, or txsatonga version? I mean, you are documenting really well your binding, and it's the type of stuff that would be great to be able to reuse by cherrypicking commits, or merging.

**Comment by Serranya** [comment]
At first i tried to use PedroHLCs and your version. But both of them did not work with sdl2.0.3.

I tried to fix yours but it was pretty big and intimidating. Since im absolutly new to vala and vapi files I wanted to start my own bindings so that im free to try things out and test them in a clean environment

But i think it would be a good idea to merge my version into yours (or the other way around).

**Comment by desiderantes** [comment]
Well, I've just fixed some compilation errors, you can try again. It's nice to freely try things, i wanted a more idiomatic binding without binding what Vala already provides, like asserts, that's why I didn't merge my work with PedroHLC. For that reason I understand if you want to keep your work separated.

**Comment by Serranya** [comment]
I can understand that you want do make the binding as idiomatic as possible.

I want to merge our work since it is just stupid to have two sets of bindings. More work for us, and more insecurity for users.

I noticed following important differences between our two repos:
- I bind functions as like `SDL_CreateTextureFromSurface` to an static method. You to an constructor.
- You dont want to bind the the **assert** subsystem (and maybe others).

I chose this implementation for the following reasons:
Functions like `SDL_CreateTextureFromSurface` can fail (return null) so binding them to an constructor is not an accurate representation (since they cant fail).

The assert api is different from what vala provides (for example it provides an popup window that ask how to procede). I also dont want to limit the use of the binding for no good reason.

If we can agree on how to handle these two points we can merge our work. You probably have also some arguments which i did not consider.

**Comment by desiderantes** [comment]
Well, some of those constructors were not binded by me. And regarding Assert, yes, i overlooked that, that popup function is really useful. SDL_Log, however, offers nothing versus GLib.Log, so I see no point in that.

**Comment by desiderantes** [comment]
Regarding SDL_assert.h: It's quite difficult to compare, mostly because GLib separates regular asserts from proper Testing, SDL2 conflates both approachs in their assert implementation. It's mostly a matter of preference, but yes, there's value in an all-in-one solution.
Other subsystems:
SDL_loadso.h: There's a better implementation of that using gmodule-2.0 (part of GLib framework)
SDL_system.h: GLib provides all of that
SDL_platform.h: Not useful on Vala
SDL_cpuinfo.h: Currently missing on bindings, truly needed.
SDL_endian.h: Already provided by GLib
SDL_bits.h: Already provided by GLib
SDL_stdinc.h: Already provided by GLib
SDL_filesystem.h: Already provided by GLib

**Comment by desiderantes** [comment]
If you want to merge the bindings, PedroHLC has a new version including my changes, you should submit patches to it at https://github.com/PedroHLC/sdl2-vapi

**Comment by Serranya** [comment]
Thank you for the information.
